import { Branch, Product, Customer, Invoice, CallReminder, LaboratoryJob, DailyCashClosing, Supplier, UserAccount } from './types';

export const INITIAL_USERS: UserAccount[] = [
  {
    id: 'u-admin',
    username: 'admin',
    fullName: 'مدير النظام (Admin)',
    role: 'admin',
    branchId: 'all',
    email: 'admin@optivision.jo',
    phone: '+962 7 9000 0001',
    pin: '1234',
    isActive: true,
    createdAt: '2026-01-01',
    lastLogin: '2026-07-25 10:15',
  },
  {
    id: 'u-accountant',
    username: 'accountant',
    fullName: 'المحاسب الرئيسي (Accountant)',
    role: 'accountant',
    branchId: 'b-main',
    email: 'accountant@optivision.jo',
    phone: '+962 7 9000 0002',
    pin: '5678',
    isActive: true,
    createdAt: '2026-01-05',
    lastLogin: '2026-07-24 16:30',
  },
  {
    id: 'u-sales',
    username: 'optician_tariq',
    fullName: 'Tariq Al-Mansoor (Optician & Sales)',
    role: 'sales_person',
    branchId: 'b-main',
    email: 'tariq@optivision.jo',
    phone: '+962 7 9000 0003',
    isActive: true,
    createdAt: '2026-02-10',
    lastLogin: '2026-07-25 09:00',
  },
  {
    id: 'u-callcenter',
    username: 'crm_layla',
    fullName: 'Layla Nasser (Call Center Agent)',
    role: 'call_center',
    branchId: 'all',
    email: 'layla@optivision.jo',
    phone: '+962 7 9000 0004',
    isActive: true,
    createdAt: '2026-03-01',
    lastLogin: '2026-07-25 08:45',
  },
  {
    id: 'u-lab',
    username: 'lab_omar',
    fullName: 'Omar Zaid (Lens Edging Lab)',
    role: 'lab_tech',
    branchId: 'b-main',
    email: 'omar@optivision.jo',
    phone: '+962 7 9000 0005',
    isActive: true,
    createdAt: '2026-03-15',
    lastLogin: '2026-07-24 18:00',
  },
];

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'b-main',
    name: 'Amman Main Branch - Mecca St',
    code: 'AMM-01',
    phone: '+962 6 550 1122',
    address: 'Mecca Street, Building 45, Amman, Jordan',
    manager: 'Tareq Al-Khatib',
    isMain: true,
  },
  {
    id: 'b-sweifieh',
    name: 'Sweifieh Mall Branch',
    code: 'SWF-02',
    phone: '+962 6 582 3344',
    address: 'Sweifieh Avenue, Level 1, Amman, Jordan',
    manager: 'Lina Al-Hassan',
    isMain: false,
  },
  {
    id: 'b-abdoun',
    name: 'Abdoun Luxury Branch',
    code: 'ABD-03',
    phone: '+962 6 593 5566',
    address: 'Abdoun Circle, Villa 12, Amman, Jordan',
    manager: 'Omar Nasser',
    isMain: false,
  },
  {
    id: 'b-irbid',
    name: 'Irbid City Branch',
    code: 'IRB-04',
    phone: '+962 2 724 8899',
    address: 'University Street, Irbid, Jordan',
    manager: 'Rania Haddad',
    isMain: false,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'p-100001',
    barcode: '100001',
    brand: 'GIORGIO ARMANI',
    model: 'G ARMANI 3042',
    description: 'G ARMANI Designer Acetate Frame',
    frameType: 'Full Rim',
    frameColor: 'Matte Black / Gold',
    size: '54-18-145',
    material: 'Premium Acetate',
    gender: 'Men',
    ageGroup: 'Adult',
    supplier: 'Luxottica Middle East',
    purchaseCost: 55,
    sellingPrice: 100,
    discountPrice: 90,
    tax: 16,
    currentQuantity: 12,
    reservedQuantity: 2,
    availableQuantity: 10,
    minimumStock: 3,
    maximumStock: 25,
    warehouse: 'Main Central Vault',
    branchId: 'b-main',
    status: 'Active',
    warrantyMonths: 12,
    createdDate: '2026-01-15',
    updatedDate: '2026-07-20',
  },
  {
    id: 'p-100002',
    barcode: '100002',
    brand: 'RAY-BAN',
    model: 'RB3025 Aviator',
    description: 'RAY-BAN Classic Gold Aviator Frame',
    frameType: 'Full Rim',
    frameColor: 'Arista Gold',
    size: '58-14-135',
    material: 'Monel Metal',
    gender: 'Unisex',
    ageGroup: 'Adult',
    supplier: 'Luxottica Middle East',
    purchaseCost: 60,
    sellingPrice: 120,
    tax: 16,
    currentQuantity: 18,
    reservedQuantity: 1,
    availableQuantity: 17,
    minimumStock: 5,
    maximumStock: 30,
    warehouse: 'Main Central Vault',
    branchId: 'b-main',
    status: 'Active',
    warrantyMonths: 12,
    createdDate: '2026-02-10',
    updatedDate: '2026-07-18',
  },
  {
    id: 'p-100003',
    barcode: '100003',
    brand: 'GUCCI',
    model: 'GG0061O Optical',
    description: 'GUCCI Oversized Square Titanium Frame',
    frameType: 'Full Rim',
    frameColor: 'Havana / Green Red Web',
    size: '53-17-140',
    material: 'Japan Titanium & Acetate',
    gender: 'Women',
    ageGroup: 'Adult',
    supplier: 'Kering Eyewear Jordan',
    purchaseCost: 140,
    sellingPrice: 240,
    discountPrice: 220,
    tax: 16,
    currentQuantity: 5,
    reservedQuantity: 0,
    availableQuantity: 5,
    minimumStock: 2,
    maximumStock: 10,
    warehouse: 'Abdoun VIP Showroom',
    branchId: 'b-abdoun',
    status: 'Active',
    warrantyMonths: 24,
    createdDate: '2026-03-01',
    updatedDate: '2026-07-22',
  },
  {
    id: 'p-100004',
    barcode: '100004',
    brand: 'OAKLEY',
    model: 'OO9102 Holbrook',
    description: 'OAKLEY Matte Black Prizm Polarized',
    frameType: 'Sunglasses',
    frameColor: 'Matte Black',
    size: '57-18-137',
    material: 'O Matter Polymer',
    gender: 'Men',
    ageGroup: 'Adult',
    supplier: 'Luxottica Middle East',
    purchaseCost: 70,
    sellingPrice: 135,
    tax: 16,
    currentQuantity: 8,
    reservedQuantity: 0,
    availableQuantity: 8,
    minimumStock: 3,
    maximumStock: 15,
    warehouse: 'Sweifieh Branch Stock',
    branchId: 'b-sweifieh',
    status: 'Active',
    warrantyMonths: 12,
    createdDate: '2026-04-12',
    updatedDate: '2026-07-19',
  },
  {
    id: 'p-100005',
    barcode: '100005',
    brand: 'PRADA',
    model: 'PR 17WV Cat-Eye',
    description: 'PRADA Elegance Acetate Eyeglasses',
    frameType: 'Full Rim',
    frameColor: 'Black Crystal',
    size: '52-16-140',
    material: 'Acetate',
    gender: 'Women',
    ageGroup: 'Adult',
    supplier: 'Luxottica Middle East',
    purchaseCost: 110,
    sellingPrice: 195,
    tax: 16,
    currentQuantity: 4,
    reservedQuantity: 1,
    availableQuantity: 3,
    minimumStock: 2,
    maximumStock: 10,
    warehouse: 'Main Central Vault',
    branchId: 'b-main',
    status: 'Active',
    warrantyMonths: 12,
    createdDate: '2026-05-01',
    updatedDate: '2026-07-21',
  },
  {
    id: 'p-200001',
    barcode: '200001',
    brand: 'ESSILOR',
    model: 'Crizal Sapphire HR 1.61',
    description: 'Essilor Anti-Reflective Blue-Cut Prescription Lenses',
    frameType: 'Ophthalmic Lens',
    frameColor: 'Clear Anti-Reflective',
    size: 'Standard Diameter 70mm',
    material: 'High Index Resin 1.61',
    gender: 'Unisex',
    ageGroup: 'Unisex',
    supplier: 'Essilor Optical Labs Amman',
    purchaseCost: 25,
    sellingPrice: 60,
    tax: 16,
    currentQuantity: 50,
    reservedQuantity: 4,
    availableQuantity: 46,
    minimumStock: 10,
    maximumStock: 100,
    warehouse: 'Central Lab Vault',
    branchId: 'b-main',
    status: 'Active',
    warrantyMonths: 12,
    createdDate: '2026-01-10',
    updatedDate: '2026-07-24',
  },
  {
    id: 'p-300001',
    barcode: '300001',
    brand: 'ACUVUE',
    model: 'Oasys Hydraclear Plus',
    description: 'Johnson & Johnson Acuvue Oasys Bi-Weekly Contact Lenses (6 pack)',
    frameType: 'Contact Lens',
    frameColor: 'Clear / Handling Tint',
    size: 'BC 8.4 / DIA 14.0',
    material: 'Senofilcon A Hydrogel',
    gender: 'Unisex',
    ageGroup: 'Unisex',
    supplier: 'J&J Medical Jordan',
    purchaseCost: 12,
    sellingPrice: 28,
    tax: 16,
    currentQuantity: 40,
    reservedQuantity: 2,
    availableQuantity: 38,
    minimumStock: 10,
    maximumStock: 80,
    warehouse: 'Main Central Vault',
    branchId: 'b-main',
    status: 'Active',
    warrantyMonths: 6,
    createdDate: '2026-02-01',
    updatedDate: '2026-07-24',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'c-101',
    name: 'Ahmad M. Al-Majali',
    phone: '+962 7 9811 2233',
    secondaryPhone: '+962 6 551 9000',
    email: 'ahmad.majali@example.com',
    address: 'Building 14, 7th Circle, Amman',
    birthDate: '1988-09-14',
    gender: 'Male',
    membershipLevel: 'Gold',
    loyaltyPoints: 340,
    notes: 'Prefers light acetate frames. Sensitive to glare.',
    createdAt: '2025-08-10',
  },
  {
    id: 'c-102',
    name: 'Sarah Al-Zoubi',
    phone: '+962 7 7654 3210',
    email: 'sarah.zoubi@example.com',
    address: 'Villa 8, Abdoun Circle, Amman',
    birthDate: '1995-12-03',
    gender: 'Female',
    membershipLevel: 'VIP',
    loyaltyPoints: 890,
    notes: 'Regular Acuvue Oasys user & Gucci designer collector.',
    createdAt: '2025-11-20',
  },
  {
    id: 'c-103',
    name: 'Mohammad K. Al-Rousan',
    phone: '+962 7 8123 4567',
    address: 'University St, Irbid',
    birthDate: '1982-04-22',
    gender: 'Male',
    membershipLevel: 'Standard',
    loyaltyPoints: 120,
    createdAt: '2026-02-14',
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-2026-001',
    invoiceNumber: 'INV-AMM-2026-0891',
    invoiceDate: '2026-07-22',
    deliveryDate: '2026-07-25',
    branchId: 'b-main',
    salesEmployee: 'Khalid Othman',
    cashier: 'Muna Al-Fayez',
    customerId: 'c-101',
    customerName: 'Ahmad M. Al-Majali',
    customerPhone: '+962 7 9811 2233',
    prescription: {
      rightEye: { sph: '-2.25', cyl: '-0.75', axis: '180' },
      leftEye: { sph: '-2.50', cyl: '-0.50', axis: '175' },
      add: '+1.50',
      a: '64',
      ipd: '64mm',
      optometristName: 'Dr. Sameer Nabulsi',
      prescriptionDate: '2026-07-22',
    },
    items: [
      {
        barcode: '100001',
        description: 'G ARMANI Designer Acetate Frame',
        itemType: 'frame',
        price: 100,
        quantity: 1,
        discount: 10,
        total: 90,
        productId: 'p-100001',
      },
      {
        barcode: '200001',
        description: 'Essilor Anti-Reflective Blue-Cut Prescription Lenses',
        itemType: 'lens',
        price: 60,
        quantity: 1,
        discount: 0,
        total: 60,
        productId: 'p-200001',
        lensDetails: {
          lensType: 'Single Vision Progressive',
          index: '1.61 High Index',
          coating: 'Crizal Sapphire Blue Block',
        },
      },
    ],
    subtotal: 160,
    discount: 10,
    tax: 24, // 16% tax on 150 net
    grandTotal: 174,
    paidAmount: 100,
    remainingBalance: 74,
    paymentMethod: 'Credit Card',
    invoiceStatus: 'Confirmed',
    deliveryStatus: 'Sent to Lab',
    warrantyTerms: '12 Months Frame & Lens Coating Warranty',
    notes: 'Customer requested anti-glare blue coating for heavy monitor screen work.',
    createdAt: '2026-07-22T10:30:00Z',
  },
  {
    id: 'inv-2026-002',
    invoiceNumber: 'INV-ABD-2026-0412',
    invoiceDate: '2026-07-20',
    deliveryDate: '2026-07-20',
    branchId: 'b-abdoun',
    salesEmployee: 'Nour Al-Huda',
    cashier: 'Omar Nasser',
    customerId: 'c-102',
    customerName: 'Sarah Al-Zoubi',
    customerPhone: '+962 7 7654 3210',
    prescription: {
      rightEye: { sph: '-1.50', cyl: '0.00', axis: '0' },
      leftEye: { sph: '-1.75', cyl: '0.00', axis: '0' },
      a: '62',
      ipd: '62mm',
      optometristName: 'Dr. Reem Qasim',
      prescriptionDate: '2026-06-15',
    },
    items: [
      {
        barcode: '100003',
        description: 'GUCCI Oversized Square Titanium Frame',
        itemType: 'frame',
        price: 240,
        quantity: 1,
        discount: 20,
        total: 220,
        productId: 'p-100003',
      },
      {
        barcode: '300001',
        description: 'Acuvue Oasys Bi-Weekly Contact Lenses (6 pack)',
        itemType: 'contact_lens',
        price: 28,
        quantity: 2,
        discount: 0,
        total: 56,
        productId: 'p-300001',
      },
    ],
    subtotal: 296,
    discount: 20,
    tax: 44.16,
    grandTotal: 320.16,
    paidAmount: 320.16,
    remainingBalance: 0,
    paymentMethod: 'Cash',
    invoiceStatus: 'Completed',
    deliveryStatus: 'Delivered',
    warrantyTerms: '24 Months Gucci International Warranty',
    notes: 'Paid in full. Express delivery at Abdoun branch.',
    createdAt: '2026-07-20T14:15:00Z',
  },
];

export const INITIAL_CALL_REMINDERS: CallReminder[] = [
  {
    id: 'cr-101',
    customerId: 'c-101',
    customerName: 'Ahmad M. Al-Majali',
    phone: '+962 7 9811 2233',
    invoiceNumber: 'INV-AMM-2026-0891',
    ruleType: 'post_sale_satisfaction',
    scheduledDate: '2026-07-25', // Today!
    status: 'Pending',
    assignedBranchId: 'b-main',
  },
  {
    id: 'cr-102',
    customerId: 'c-102',
    customerName: 'Sarah Al-Zoubi',
    phone: '+962 7 7654 3210',
    invoiceNumber: 'INV-ABD-2026-0412',
    ruleType: '1_month_contact_lens_reminder',
    scheduledDate: '2026-08-20',
    status: 'Pending',
    assignedBranchId: 'b-abdoun',
  },
  {
    id: 'cr-103',
    customerId: 'c-103',
    customerName: 'Mohammad K. Al-Rousan',
    phone: '+962 7 8123 4567',
    ruleType: '6_month_eye_check',
    scheduledDate: '2026-08-14',
    status: 'Pending',
    assignedBranchId: 'b-irbid',
  },
];

export const INITIAL_LAB_JOBS: LaboratoryJob[] = [
  {
    id: 'lab-901',
    jobOrderNumber: 'JOB-2026-8801',
    invoiceNumber: 'INV-AMM-2026-0891',
    customerName: 'Ahmad M. Al-Majali',
    branchId: 'b-main',
    frameBarcode: '100001',
    frameDescription: 'G ARMANI Designer Acetate Frame',
    rightEyePrescription: 'SPH -2.25 / CYL -0.75 / AXIS 180 / ADD +1.50',
    leftEyePrescription: 'SPH -2.50 / CYL -0.50 / AXIS 175 / ADD +1.50',
    lensType: 'Single Vision Progressive 1.61',
    coating: 'Crizal Sapphire Blue Block',
    technicianName: 'Samer Lab Tech',
    status: 'Lens Edging',
    sentDate: '2026-07-22',
    notes: 'Special beveling required for thin frame edge.',
  },
];

export const INITIAL_CASH_CLOSINGS: DailyCashClosing[] = [
  {
    id: 'cash-001',
    branchId: 'b-main',
    date: '2026-07-24',
    openingBalance: 150,
    cashSales: 480,
    cardSales: 620,
    expenses: 30,
    cashInSafe: 600,
    reconciliationDifference: 0,
    closedBy: 'Tareq Al-Khatib',
    status: 'Closed',
    notes: 'All receipts balanced perfectly.',
  },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-01',
    name: 'Luxottica Middle East Ltd.',
    contactPerson: 'Fadi Karam',
    phone: '+971 4 881 9900',
    email: 'fadi.karam@luxottica.com',
    balance: 14500,
    address: 'Dubai Silicon Oasis, UAE',
  },
  {
    id: 'sup-02',
    name: 'Kering Eyewear Jordan',
    contactPerson: 'Dalia Mansour',
    phone: '+962 6 560 7711',
    email: 'orders.jordan@kering.com',
    balance: 8200,
    address: 'Shmeisani Commercial Complex, Amman',
  },
  {
    id: 'sup-03',
    name: 'Essilor Optical Labs Amman',
    contactPerson: 'Eng. Ziad Quraan',
    phone: '+962 6 463 2211',
    email: 'lab.amman@essilor.jo',
    balance: 3400,
    address: 'King Hussein Street, Downtown Amman',
  },
];

export const INITIAL_PURCHASE_ORDERS: any[] = [];
